version: '3.4'

services: 

  frontend:
    image: storeimage
    build:
      context: .
      dockerfile: DockerfileStore
    environment: 
      - ProductEndpoint=http://backend:8080
      - ImagePrefix=https://solid-guide-qjwwrpg647h4q9r-5902.app.github.dev/images
    ports:
      - "32000:8080"
    depends_on: 
      - backend
  backend:
    image: productservice
    build: 
      context: .
      dockerfile: DockerfileProducts
    ports: 
      - "32001:8080"