---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: storefrontend
spec:
    replicas: 1
    template:
      metadata:
          labels:
            app: storefrontend
      spec:
          containers:
              - name: storefrontend
                image: ksquare2020/storeimage:latest
                ports:
                  - containerPort: 80
                env:
                  - name: ASPNETCORE_URLS
                    value: http://*:80
                  - name: ProductEndpoint
                    value: http://productsbackend
                  - name: ImagePrefix
                    value: https://solid-guide-qjwwrpg647h4q9r-5902.app.github.dev/images
    selector:
        matchLabels:
            app: storefrontend
---
apiVersion: v1
kind: Service
metadata:
    name: storefrontend
spec:
    type: NodePort
    ports:
       - port: 80
         targetPort: 80
         nodePort: 32000
    selector:
        app: storefrontend